version: '3'

services:
  challange:
    build: .
    restart: on-failure:5
    env_file:
      - ./.env
    volumes:
      - ./files:/var/tmp/files 
      - ./files/archive:/var/tmp/files/archive
      - ./src:/app/src

